# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-09 10:50
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('record_date', models.DateTimeField(default=datetime.datetime.now, unique=True)),
                ('julian_day', models.SmallIntegerField()),
                ('day_frac', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=7, verbose_name='Fraction of Day')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=5, null=True, verbose_name='FTemperature (\xb0C)')),
                ('ph_units', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=5, null=True)),
                ('stream_depth', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=5, null=True)),
                ('sp_cond', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=6, null=True, verbose_name='Specific Conductance (uS/cm)')),
                ('turbidity_NTU', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=8, null=True)),
                ('ph_mv', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=7, null=True)),
                ('salinity_ps', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=5, null=True, verbose_name='Potential Soil Salinity')),
                ('comment', models.TextField(blank=True, null=True)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='streamwater_waterquality', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Water Quality',
            },
        ),
    ]
